"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['neckatt.py']
DATA_FILES = ["haarcascade_frontalface_alt2.xml","txt.icns"]
OPTIONS = {'argv_emulation': False,'iconfile':'./txt.icns','includes':['ctypes','numpy','cv2','PIL','image'],
    'frameworks': [ '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libffi.7.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libtcl8.6.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libpanelw.6.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libformw.6.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libmenuw.6.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libz.1.2.12.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/liblzma.5.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libsqlite3.0.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libc++.1.0.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libncursesw.6.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libtinfow.6.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libcrypto.1.1.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libssl.1.1.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libhistory.8.1.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libreadline.8.1.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libtk8.6.dylib',
                    '/Users/adamlee/opt/anaconda3/envs/python37_neckatt/lib/libpython3.7m.dylib'],
    'plist': {
        'NSCameraUsageDescription':'$$$$$$$ 请同意使用摄像头，并重启应用 $$$$$$$$$$','NSHumanReadableCopyright': u"版权所有 © 2022, lida2012@foxmail.com",'CFBundleVersion': "2022-06-21-0.1.0"}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)



